version: "3"

services:

  filebrowser:
    image: hurlenko/filebrowser:latest
    environment:
      - UID=1000
      - GID=1000
      - TZ=Europe/Madrid
    ports:
      - "8200:8080"
    volumes:
      - /home/user/data:/data
      - ./fb-config:/config
